site_name: OS Archive

# Theme Configuration
theme:
  name: terminal

# Base URL Configuration
base_url: /The-Mainframe/
sitw_url: https://sinclair-speccy.github.io/The-Mainframe/

# Navigation Configuration
nav:
  - Welcome: index.md
  - Introduction: introduction.md

# Markdown Extensions
markdown_extensions:
  - rss
  - markdown_captions
  - search
  - git-revision-date-localized
  - i18n
  - autorefs
  
# Additional Configuration Options (Optional)
# Example: Configure Google Analytics for your site (uncomment and replace with your GA tracking ID)
# google_analytics: UA-XXXXX-X
